// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADVL3W0fdJprGvc_fbfEHr_zcq1edenCQ',
    appId: '1:1060939038503:web:961b5e7004b72369c0b302',
    messagingSenderId: '1060939038503',
    projectId: 'firat-bilgisayar-sisteml-4f89e',
    authDomain: 'firat-bilgisayar-sisteml-4f89e.firebaseapp.com',
    storageBucket: 'firat-bilgisayar-sisteml-4f89e.appspot.com',
    measurementId: 'G-TYFFS7N49D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsAaOO5gDgeamaEmHVaqmchq2WT0FuOko',
    appId: '1:1060939038503:android:aa7266d08b284eb3c0b302',
    messagingSenderId: '1060939038503',
    projectId: 'firat-bilgisayar-sisteml-4f89e',
    storageBucket: 'firat-bilgisayar-sisteml-4f89e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhFeGVKEftrrz_Unkt---c00XP_TCq0Aw',
    appId: '1:1060939038503:ios:d98e8feb3cd59d92c0b302',
    messagingSenderId: '1060939038503',
    projectId: 'firat-bilgisayar-sisteml-4f89e',
    storageBucket: 'firat-bilgisayar-sisteml-4f89e.appspot.com',
    iosClientId: '1060939038503-ctsqjj8dho8sjbnoaoujjkambucn64gq.apps.googleusercontent.com',
    iosBundleId: 'com.example.firatBilgisayarSistemleri',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhFeGVKEftrrz_Unkt---c00XP_TCq0Aw',
    appId: '1:1060939038503:ios:05e6281418d2d484c0b302',
    messagingSenderId: '1060939038503',
    projectId: 'firat-bilgisayar-sisteml-4f89e',
    storageBucket: 'firat-bilgisayar-sisteml-4f89e.appspot.com',
    iosClientId: '1060939038503-njt7mi1kafkckh1hs9gmnimltrbt1fvf.apps.googleusercontent.com',
    iosBundleId: 'com.example.firatBilgisayarSistemleri.RunnerTests',
  );
}
